### ISSUE TITLE
拨号VPN页面Internal Server Error

### ISSUE THREAD

**Issue by duluosheng** [alibaba/FlexGW#10]
从后台日志中得到的错误信息是：
2018-01-10 17:48:32,734 INFO: [Request Message]: GET https://x.x.x.x/vpn/dial/ 
2018-01-10 17:48:32,761 ERROR: [Exception Request]: invalid literal for int() with base 10: 'Tue Jan  9 16:34:28 2018'
2018-01-10 17:48:32,762 ERROR: Exception on /vpn/dial/ [GET]
Traceback (most recent call last):
  File "/usr/local/flexgw/python/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/flexgw/python/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/flexgw/python/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/flexgw/python/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/flexgw/python/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/flexgw/python/lib/python2.7/site-packages/flask_login.py", line 758, in decorated_view
    return func(*args, **kwargs)
  File "/usr/local/flexgw/website/vpn/dial/views.py", line 34, in index
    accounts = get_accounts(status=True)
  File "/usr/local/flexgw/website/vpn/dial/services.py", line 253, in get_accounts
    account['ct'] = datetime.fromtimestamp(int(status['ct'])).strftime('%Y-%m-%d %H:%M:%S')
ValueError: invalid literal for int() with base 10: 'Tue Jan  9 16:34:28 2018'

系统版本：CentOS 6

**Comment by chatmoo** [comment]
openvpn 建议采用2.3.11

**Comment by duluosheng** [comment]
修改website/vpn/dial/services.py，
将account['ct'] = datetime.fromtimestamp(int(status['ct'])).strftime('%Y-%m-%d %H:%M:%S')
改为：account['ct'] = status['ct']
